version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: crossfhir
    main: ./cmd/crossfhir
    binary: crossfhir
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - README*
      - LICENSE*

checksum:
  name_template: 'checksums.txt'