services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  duckdb:
    image: datacatering/duckdb:v1.1.1
    volumes:
      - ./tmp/duckdb:/data
    ports:
      - "4000:4000"
    environment:
      - DUCKDB_ALLOW_UNSIGNED=1

volumes:
  postgres_data: